[package]
name = "bitpatterns"
version = "1.0.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitpatterns-proc-macro = { version = "1.0", path = "../bitpatterns-proc-macro" }
